### ISSUE TITLE
I have a few questions

### ISSUE THREAD

**Issue by cpkt9762** [dougEfresh/selene-helius-sdk#13]
1. The 'owner' in the 'struct GetTokenAccountsParams' should be changed to 'mint'.
2. The 'enum TransactionType' should add 'CreatePool', 'AddLiquidity', and 'WithdrawLiquidity'."

**Comment by dougEfresh** [comment]
1. Looks like the [docs](https://docs.helius.dev/compression-and-das-api/digital-asset-standard-das-api/get-token-accounts) use `owner`
2. I do not see these defined in the typescript  [sdk](https://github.com/helius-labs/helius-sdk/blob/main/src/types/enums.ts#21)

**Comment by dougEfresh** [comment]
oh, I was looking for CreatePool. In TypeScript, they   call it CREATE_POOL

**Comment by dougEfresh** [comment]
@cpkt9762 I released version [0.2.1](https://crates.io/crates/selene-helius-sdk/0.2.1)
