### ISSUE TITLE
Raise an issue: Add pub timestamp: u64 to struct EnhancedTransaction.

### ISSUE THREAD

**Issue by cpkt9762** [dougEfresh/selene-helius-sdk#17]
selene-helius-sdk\src\api\types\enhanced.rs 
pub struct EnhancedTransaction {
  pub account_data: Vec<AccountData>,
  pub description: String,
  #[serde(rename = "type")]
  pub transaction_type: TransactionType,
  pub source: Source,
  pub fee: i32,
  pub fee_payer: String,
  pub signature: String,
  pub slot: i32,
  pub timestamp: u64,
  pub native_transfers: Option<Vec<NativeTransfer>>,
  pub token_transfers: Option<Vec<TokenTransfer>>,
  pub transaction_error: Option<TransactionError>,
  pub instructions: Vec<Instruction>,
  pub events: TransactionEvent,
} 

.......
{"accounts":.....],
"nativeTransfers":[.........],
"signature":"5e5U2qDg4hFkUCckgZkrDz8uBr6mj2JfMn68Sobp9dYLHWBm12KCBmgUpuwMeDZvEE6vDrg67qp1JLqg69zwYruB",
"slot":250617062,
"source":"RAYDIUM",
"timestamp":1708969765,
"tokenTransfers":[.......],
"transactionError":null,
"type":"CREATE_POOL"}

**Comment by dougEfresh** [comment]
@cpkt9762 0.2.2 is publish
